version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./artifacts/rabbitmq/data/:/var/lib/rabbitmq/
      - ./artifacts/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - nestjs-ddd-example-network

  postgres:
    container_name: nestjs-ddd-example-postgres
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
    volumes:
      - ./artifacts/postgres:/var/lib/postgresql/data/
      - ./artifacts/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nestjs-ddd-example-network

  pgadmin:
    container_name: nestjs-ddd-example-pgadmin
    image: "dpage/pgadmin4"
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - "5050:80"
    networks:
      - nestjs-ddd-example-network

networks:
  nestjs-ddd-example-network:
